version: "2"
services:
  ika:
    build: ika
    restart: always
    depends_on:
      - mysql
    ports:
      - "0.0.0.0:5558:80"
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ik4
      - MYSQL_DATABASE=ika
    volumes:
      - /srv/data/ikakulttuuri/mysql:/var/lib/mysql
