version: "2"
services:
  ika:
    build: ika
    restart: always
    depends_on:
      - mysql
    ports:
      - "0.0.0.0:5558:80"
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xeediepashaixoh8gooch0yoogieDahjain2eeque8chie6Oeyohthei7iwauwai8ohsh
      - MYSQL_DATABASE=ika
    volumes:
      - /srv/data/aikain/ikariam/cultures.s4-fi.ikariam.aika.in/mysql:/var/lib/mysql
